language: node_js
node_js:
  - "0.11"
  - "0.10"
branches:
  only:
    - master
    - development
notifications:
  irc: "chat.freenode.net#avon"
before_install: npm install -g grunt-cli
install: npm install
